### ISSUE TITLE
Possibility to set correct timezone?

### ISSUE THREAD

**Issue by ralf-koe** [qvicksilver/docker-logitechmediaserver#1]
It'll be nice, if a possibility for setting the correct timezone will be included. It's also manually possible, but within the container/setup it will be easier.

**Comment by qvicksilver** [comment]
Didn't know I had a userbase :) I'll look into making that happen, would specifying the timezone as an environment variable be OK?

**Comment by ralf-koe** [comment]
:-)

Environment variable will be very good.

Main problem was, that the endpoint show the right time but the alarm clock was too late :-O.

"Europe/Berlin" within the /config/etc/timezone should help

I set it directly in /etc/timezone, for the running system ok.

**Comment by qvicksilver** [comment]
Does this do the trick for you: f3555d6f28d428f1adfc86fbb3ff7e9163b0cebb
