### ISSUE TITLE
Using the YouTube plugin isn't possible

### ISSUE THREAD

**Issue by schmic** [qvicksilver/docker-logitechmediaserver#2]
`SSL required (try to install it using CPAN and/or on Linux do "sudo apt-get install libio-socket-ssl-perl libnet-ssleay-perl")`

Anything I can do about it?

**Comment by schmic** [comment]
Installed the packages with apt in the running container fixed it, would you like to add them to your image, please? :)

**Comment by qvicksilver** [comment]
Sure! Latest image should contain what you need.
