### ISSUE TITLE
container not exposing in the specified ports

### ISSUE THREAD

**Issue by deep92r** [qvicksilver/docker-logitechmediaserver#3]
i've pulled ur docker image ,and run the container ,after entering the ip address in my browser ,it shows nothing.

pi@raspberrypi:~/new1/docker-logitechmediaserver $ docker run -d -p 9000:9000 -p 3483:3483 -p3483:3483/udp -v  ${home/pi/Downloads}:/srv/music qvicksilver/logitechmediaserver
ffcf5937e690c17ce9780c12e80d0846925260a3b7442d5251ce90e5d5b5a12e

The container will start and exited within few seconds

**Comment by qvicksilver** [comment]
ARM is not supported, pretty sure thats why :/
